package _codeMessage

type CodeMessage struct {
	Code    int
	Message string
}

func New(code int, message string) *CodeMessage {
	return &CodeMessage{
		Code:    code,
		Message: message,
	}
}

var (
	ErrNone                               = New(100000, "成功")
	ErrDefault                            = New(1, "系统繁忙，稍后重试")
	ErrParameter                          = New(2, "参数错误")
	ErrAesNewCipher                       = New(101, "")
	ErrBase64RawURLEncodingDecodeString   = New(102, "")
	ErrGrpcDial                           = New(103, "")
	ErrPbNewServiceClientCall             = New(104, "")
	ErrCmdOutput                          = New(105, "")
	ErrHttpRequestParseForm               = New(106, "")
	ErrHttpRequestParseMultipartForm      = New(107, "")
	ErrJsonNewDecoderDecode               = New(108, "")
	ErrHttpRequestBodyClose               = New(109, "")
	ErrOsOpen                             = New(110, "")
	ErrCsvNewReaderRead                   = New(111, "")
	ErrCsvNewReaderReadAll                = New(112, "")
	ErrOsFileClose                        = New(113, "")
	ErrOsOpenFile                         = New(114, "")
	ErrCsvNewWriterWrite                  = New(115, "")
	ErrOsStat                             = New(116, "")
	ErrOsMkdirAll                         = New(117, "")
	ErrOsRemoveAll                        = New(118, "")
	ErrOsRename                           = New(119, "")
	ErrOsIoCopy                           = New(120, "")
	ErrOsCreate                           = New(121, "")
	ErrOsFileSeek                         = New(122, "")
	ErrIoUtilReadAll                      = New(123, "")
	ErrOsReadFile                         = New(124, "")
	ErrOsFileWriteAt                      = New(125, "")
	ErrHashHashWrite                      = New(126, "")
	ErrJsonMarshal                        = New(127, "")
	ErrJsonUnmarshal                      = New(128, "")
	ErrGoMailDialerDialAndSend            = New(129, "")
	ErrSyscallMmap                        = New(130, "")
	ErrSyscallSyscall                     = New(131, "")
	ErrSyscallMunmap                      = New(132, "")
	ErrBcryptGenerateFromPassword         = New(133, "")
	ErrMapKeyNotExists                    = New(134, "KEY不存在")
	ErrSliceOutOfIndex                    = New(135, "索引超出边界")
	ErrRsaGenerateKey                     = New(136, "")
	ErrX509MarshalPKCS8PrivateKey         = New(137, "")
	ErrX509MarshalPKIXPublicKey           = New(138, "")
	ErrRsaEncryptPKCS1v15                 = New(139, "")
	ErrX509ParsePKCS8PrivateKey           = New(140, "")
	ErrRsaDecryptPKCS1v15                 = New(141, "")
	ErrExcelizeOpenFile                   = New(142, "")
	ErrExcelizeFileRows                   = New(143, "")
	ErrExcelizeFileRowsRowIteratorColumns = New(144, "")
	ErrExcelizeFileGetRows                = New(145, "")
	ErrExcelizeFileClose                  = New(146, "")
	ErrExcelizeCoordinatesToCellName      = New(147, "")
	ErrExcelizeFileCloseSetSheetRow       = New(148, "")
	ErrExcelizeFileSaveAs                 = New(149, "")
	ErrTimeParseInLocation                = New(150, "")
	ErrSqlOpen                            = New(151, "")
	ErrSqlTxExec                          = New(152, "")
	ErrSqlDBExec                          = New(153, "")
	ErrSqlTxQuery                         = New(154, "")
	ErrSqlDBQuery                         = New(155, "")
	ErrSqlRowsClose                       = New(156, "")
	ErrSqlRowsColumns                     = New(157, "")
	ErrSqlRowsScan                        = New(158, "")
	ErrSqlResultLastInsertId              = New(159, "")
	ErrSqlResultRowsAffected              = New(160, "")
	ErrSqlDBBegin                         = New(161, "")
	ErrSqlTxCommit                        = New(162, "")
	ErrSqlTxRollback                      = New(163, "")
	ErrAccessControlAllowOrigin           = New(164, "跨域阻止")
	ErrResourceNotExists                  = New(165, "资源不存在")
)
